/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eieggugfwcraysawdulo";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZWdndWdmd2NyYXlzYXdkdWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Nzc2MDcsImV4cCI6MjA3NDA1MzYwN30.Bkwgg8PHZYqS-JW0mzVLEVQGIpCCUSuFOxIWsNL8n8g";
